data_mode: cifar10
teaching_mode: omniscient
same_feat_space: True
n_iter: 800 # 500 # 200
learning_rate: 1e-3
batch_size: 128
nb_train: 5000
nb_test: 500
dim: 24 # 784 # 24
n_teacher_runs: 2 # 30
class_1: 3
class_2: 5
gd_n: 300 # 1000
lr_factor: 2
optim: AMSGrad
hidden_dim: 32
latent_dim: 24
n_unroll: 1000 # 1000
n_unroll_blocks: 0 # 40
n_epochs: 2 # 200
start_saving: 1
save_frequency: 1
label_dim: 10
n_critic: 1
log_interval: 100
n_classes: 10
model_name: Blackbox_CIFAR10
lr: 0.1
decay: 0.0001
seed: 1
channels: 3
img_size: 32
augment: True
train_student: True
train_sgd: True
train_baseline: True
n_query_classes: 10
num_workers: 10 # 10
