data_mode: cifar10
teaching_mode: omniscient
same_feat_space: True
n_iter: 800 # 500 # 200
learning_rate: 1e-3
batch_size: 128
nb_train: 5000
nb_test: 500
dim: 24 # 784 # 24
n_teacher_runs: 2 # 30
class_1: 3
class_2: 5
gd_n: 300 # 1000
lr_factor: 2
optim: AMSGrad
hidden_dim: 32
latent_dim: 24
n_unroll: 1000 # 1000
n_unroll_blocks: 10 # 40
n_epochs: 50 # 200
start_saving: 1
save_frequency: 1
label_dim: 10
n_critic: 1
log_interval: 10000
n_classes: 10
model_name: Blackbox_CIFAR10
lr: 0.001
momentum: 0.9
nesterov: True
weight_decay: 0.0005
decay: 0.0001
channels: 3
img_size: 32
augment: False
train_student: True
train_sgd: True
train_baseline: True
n_query_classes: 10
num_workers: 0 # 10
action_space: 3
n_pg_epochs: 3
n_tries: 40
n_weight_update: 5 # 5
n_z_update: 15 # 20
layers: 40
widen_factor: 4
droprate: 0.3
model: CNN15
epsilon: 0.1
n_in: 1024
