data_mode: linearly_seperable
teaching_mode: omniscient
same_feat_space: True
n_iter: 300
learning_rate: 1e-4
batch_size: 1
nb_train: 1200
nb_test: 400
dim: 2
n_teacher_runs: 10
class_1: 0
class_2: 1
lr_factor: 15000 # 10000
gd_n: 300
