data_mode: mnist
teaching_mode: omniscient
same_feat_space: True
n_iter: 800 # 500 # 200
learning_rate: 1e-3
batch_size: 256
nb_train: 5000
nb_test: 500
dim: 24 # 784 # 24
n_teacher_runs: 2 # 30
class_1: 3
class_2: 5
gd_n: 300 # 1000
lr_factor: 2
optim: AMSGrad
hidden_dim: 32
latent_dim: 24
n_unroll: 1000 # 1000
n_unroll_blocks: 40
n_epochs: 100
start_saving: 1
save_frequency: 1
label_dim: 10
n_critic: 1
log_interval: 100
n_classes: 10
