data_mode: fashion_mnist
teaching_mode: omniscient
same_feat_space: True
n_iter: 300 # 800 # 500 # 200
learning_rate: 1e-3
batch_size: 128
nb_train: 10000
nb_test: 1000
dim: 24 # 784 # 24
n_teacher_runs: 30
class_1: 3
class_2: 5
gd_n: 300 # 1000
gd_n_label: 300 # 1000
lr_factor: 2
optim: AMSGrad
hidden_dim: 32
latent_dim: 24 # 24
n_unroll: 1000 # 1000
n_unroll_blocks: 10 # 40
n_epochs: 70 # 35
start_saving: 0
save_frequency: 1
label_dim: 10
n_critic: 1
log_interval: 100
n_classes: 10
model_name: Blackbox_MNIST
channels: 1
img_size: 28
n_query_classes: 10
train_student: True
train_sgd: True
train_baseline: True
train_wstar: True
generator_type: cgan
label_norm: 2
label_alpha: 0.002
model: MLP
epsilon: 0.1
n_weight_update: 5 # 5
n_z_update: 15 # 20
n_in: 784
n_tries: 30
action_space: 2
n_pg_epochs: 3
num_workers: 0 # 10
lr: 0.001
