data_mode: moon
teaching_mode: omniscient
same_feat_space: True
n_iter: 300 # 1500
learning_rate: 1e-4
batch_size: 1
nb_train: 400
nb_test: 200
dim: 2
n_teacher_runs: 20
class_1: 0
class_2: 1
lr_factor: 100000
gd_n: 300
